/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author Pablo
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        amountSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        codeText = new javax.swing.JTextField();
        addArticleButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        finishBillButton = new javax.swing.JButton();
        removeRowButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        selectClientButton = new javax.swing.JButton();
        selectedClientLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        discountText = new javax.swing.JTextField();
        subTotalLabel = new javax.swing.JLabel();
        subTotalText = new javax.swing.JTextField();
        totalLabel = new javax.swing.JLabel();
        totalText = new javax.swing.JTextField();
        billNumberLabel = new javax.swing.JLabel();
        billNumberText = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        newBillItem = new javax.swing.JMenuItem();
        billRefundItem = new javax.swing.JMenuItem();
        registerItem = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        registerArticleItem = new javax.swing.JMenuItem();
        registerClientItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        editArticleItem = new javax.swing.JMenuItem();
        editClientItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        queryBillsItem = new javax.swing.JMenuItem();
        queryRefundsItem = new javax.swing.JMenuItem();
        queryArticlesItem = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        preferencesItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Código del artículo:");

        addArticleButton.setText("Añadir");

        removeButton.setText("Quitar");

        finishBillButton.setText("Finalizar Devolución");

        removeRowButton.setText("Eliminar Fila");

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nº Articulos", "Código", "Nombre", "Cantidad", "Precio", "IVA", "Detalles"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(mainTable);

        selectClientButton.setText("Seleccionar Cliente");

        selectedClientLabel.setText("Ningun Cliente Seleccionado");

        jLabel2.setText("DESCUENTO(%): ");

        subTotalLabel.setText("SUBTOTAL:");

        totalLabel.setText("TOTAL:");

        billNumberLabel.setText("Nº Factura: ");

        billNumberText.setText("0");

        jMenu1.setText("Factura");

        newBillItem.setText("Nueva Factura");
        jMenu1.add(newBillItem);

        billRefundItem.setText("Nueva Devolución");
        jMenu1.add(billRefundItem);

        jMenuBar1.add(jMenu1);

        registerItem.setText("Alta/Devolución");

        jMenu5.setText("Alta");

        registerArticleItem.setText("Artículo");
        jMenu5.add(registerArticleItem);

        registerClientItem.setText("Cliente");
        jMenu5.add(registerClientItem);

        registerItem.add(jMenu5);

        editMenu.setText("Modificación");

        editArticleItem.setText("Artículo");
        editMenu.add(editArticleItem);

        editClientItem.setText("Cliente");
        editMenu.add(editClientItem);

        registerItem.add(editMenu);

        jMenuBar1.add(registerItem);

        jMenu3.setText("Consultas");

        queryBillsItem.setText("Facturas");
        jMenu3.add(queryBillsItem);

        queryRefundsItem.setText("Devoluciones");
        jMenu3.add(queryRefundsItem);

        queryArticlesItem.setText("Artículos");
        jMenu3.add(queryArticlesItem);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Configuración");

        preferencesItem.setText("Preferencias");
        jMenu4.add(preferencesItem);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(amountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codeText, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addArticleButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removeRowButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(finishBillButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectClientButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectedClientLabel)
                        .addGap(78, 78, 78)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(discountText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subTotalLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subTotalText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(billNumberLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(billNumberText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(totalLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalText, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(codeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addArticleButton)
                    .addComponent(removeButton)
                    .addComponent(finishBillButton)
                    .addComponent(removeRowButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectClientButton)
                    .addComponent(selectedClientLabel)
                    .addComponent(jLabel2)
                    .addComponent(discountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subTotalLabel)
                    .addComponent(subTotalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalLabel)
                    .addComponent(totalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billNumberLabel)
                    .addComponent(billNumberText)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addArticleButton;
    private javax.swing.JSpinner amountSpinner;
    private javax.swing.JLabel billNumberLabel;
    private javax.swing.JLabel billNumberText;
    private javax.swing.JMenuItem billRefundItem;
    private javax.swing.JTextField codeText;
    private javax.swing.JTextField discountText;
    private javax.swing.JMenuItem editArticleItem;
    private javax.swing.JMenuItem editClientItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JButton finishBillButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mainTable;
    private javax.swing.JMenuItem newBillItem;
    private javax.swing.JMenuItem preferencesItem;
    private javax.swing.JMenuItem queryArticlesItem;
    private javax.swing.JMenuItem queryBillsItem;
    private javax.swing.JMenuItem queryRefundsItem;
    private javax.swing.JMenuItem registerArticleItem;
    private javax.swing.JMenuItem registerClientItem;
    private javax.swing.JMenu registerItem;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton removeRowButton;
    private javax.swing.JButton selectClientButton;
    private javax.swing.JLabel selectedClientLabel;
    private javax.swing.JLabel subTotalLabel;
    private javax.swing.JTextField subTotalText;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JTextField totalText;
    // End of variables declaration//GEN-END:variables
}
